export const SIDE_MENU_CLOSE="SIDE_MENU_CLOSE";
export const LOGIN_USER="LOGIN_USER";
export const LOGOUT_USER="LOGOUT_USER";
export const SERVER_REQUESTING="SERVER_REQUESTING";
export const SERVER_CALLED_BACKED="SERVER_CALLED_BACKED";
export const SHOW_SNACKBAR="SHOW_SNACKBAR";
export const USER_PERMITS_LOADED="USER_PERMIT_LOADED";
